# syntax=docker/dockerfile:1.7

FROM node:20-bookworm-slim AS deps
WORKDIR /app

RUN apt-get update \
  && apt-get install -y --no-install-recommends python3 make g++ \
  && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./
RUN npm install --no-audit --no-fund

FROM node:20-bookworm-slim AS builder
WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

ARG NEXT_PUBLIC_PRIVY_APP_ID=""
ARG NEXT_PUBLIC_PRIVY_CLIENT_ID=""
ARG NEXT_PUBLIC_WEB_PUSH_PUBLIC_KEY=""
ARG NEXT_PUBLIC_APP_URL=""
ARG NEXT_PUBLIC_HYPERLIQUID_TESTNET="true"
ARG NEXT_PUBLIC_MONAD_TESTNET="true"
ARG NEXT_PUBLIC_ENABLE_EMERGENCY_BRIDGE_FUND="false"
ARG NEXT_PUBLIC_ENABLE_DIRECT_UNIT_DEPOSIT="false"
ARG NEXT_PUBLIC_MIN_MON_DEPOSIT="450"
ARG NEXT_PUBLIC_MONAD_MAINNET_RPC_URL=""
ARG NEXT_PUBLIC_MONAD_TESTNET_RPC_URL=""
ARG NEXT_PUBLIC_VAULT_ADDRESS=""
ARG NEXT_PUBLIC_MAINNET_VAULT_HOTFIX_ADDRESS=""
ARG NEXT_PUBLIC_MONAD_MAINNET_VAULT_ADDRESS=""
ARG NEXT_PUBLIC_MONAD_TESTNET_VAULT_ADDRESS=""
ARG NEXT_PUBLIC_VAULT_ADDRESS_MAINNET=""
ARG NEXT_PUBLIC_VAULT_ADDRESS_TESTNET=""
ARG NEXT_PUBLIC_HCLAW_TOKEN_ADDRESS=""
ARG NEXT_PUBLIC_HCLAW_TOKEN_ADDRESS_MAINNET=""
ARG NEXT_PUBLIC_HCLAW_TOKEN_ADDRESS_TESTNET=""
ARG NEXT_PUBLIC_MONAD_MAINNET_HCLAW_TOKEN_ADDRESS=""
ARG NEXT_PUBLIC_MONAD_TESTNET_HCLAW_TOKEN_ADDRESS=""
ARG NEXT_PUBLIC_HCLAW_LOCK_ADDRESS=""
ARG NEXT_PUBLIC_HCLAW_LOCK_ADDRESS_MAINNET=""
ARG NEXT_PUBLIC_HCLAW_LOCK_ADDRESS_TESTNET=""
ARG NEXT_PUBLIC_MONAD_MAINNET_HCLAW_LOCK_ADDRESS=""
ARG NEXT_PUBLIC_MONAD_TESTNET_HCLAW_LOCK_ADDRESS=""
ARG NEXT_PUBLIC_HCLAW_POLICY_ADDRESS=""
ARG NEXT_PUBLIC_HCLAW_REWARDS_ADDRESS=""
ARG NEXT_PUBLIC_AGENTIC_LP_VAULT_ADDRESS=""
ARG NEXT_PUBLIC_BUILDER_ADDRESS=""
ARG NEXT_PUBLIC_BUILDER_FEE=""

ENV NEXT_PUBLIC_PRIVY_APP_ID="${NEXT_PUBLIC_PRIVY_APP_ID}"
ENV NEXT_PUBLIC_PRIVY_CLIENT_ID="${NEXT_PUBLIC_PRIVY_CLIENT_ID}"
ENV NEXT_PUBLIC_WEB_PUSH_PUBLIC_KEY="${NEXT_PUBLIC_WEB_PUSH_PUBLIC_KEY}"
ENV NEXT_PUBLIC_APP_URL="${NEXT_PUBLIC_APP_URL}"
ENV NEXT_PUBLIC_HYPERLIQUID_TESTNET="${NEXT_PUBLIC_HYPERLIQUID_TESTNET}"
ENV NEXT_PUBLIC_MONAD_TESTNET="${NEXT_PUBLIC_MONAD_TESTNET}"
ENV NEXT_PUBLIC_ENABLE_EMERGENCY_BRIDGE_FUND="${NEXT_PUBLIC_ENABLE_EMERGENCY_BRIDGE_FUND}"
ENV NEXT_PUBLIC_ENABLE_DIRECT_UNIT_DEPOSIT="${NEXT_PUBLIC_ENABLE_DIRECT_UNIT_DEPOSIT}"
ENV NEXT_PUBLIC_MIN_MON_DEPOSIT="${NEXT_PUBLIC_MIN_MON_DEPOSIT}"
ENV NEXT_PUBLIC_MONAD_MAINNET_RPC_URL="${NEXT_PUBLIC_MONAD_MAINNET_RPC_URL}"
ENV NEXT_PUBLIC_MONAD_TESTNET_RPC_URL="${NEXT_PUBLIC_MONAD_TESTNET_RPC_URL}"
ENV NEXT_PUBLIC_VAULT_ADDRESS="${NEXT_PUBLIC_VAULT_ADDRESS}"
ENV NEXT_PUBLIC_MAINNET_VAULT_HOTFIX_ADDRESS="${NEXT_PUBLIC_MAINNET_VAULT_HOTFIX_ADDRESS}"
ENV NEXT_PUBLIC_MONAD_MAINNET_VAULT_ADDRESS="${NEXT_PUBLIC_MONAD_MAINNET_VAULT_ADDRESS}"
ENV NEXT_PUBLIC_MONAD_TESTNET_VAULT_ADDRESS="${NEXT_PUBLIC_MONAD_TESTNET_VAULT_ADDRESS}"
ENV NEXT_PUBLIC_VAULT_ADDRESS_MAINNET="${NEXT_PUBLIC_VAULT_ADDRESS_MAINNET}"
ENV NEXT_PUBLIC_VAULT_ADDRESS_TESTNET="${NEXT_PUBLIC_VAULT_ADDRESS_TESTNET}"
ENV NEXT_PUBLIC_HCLAW_TOKEN_ADDRESS="${NEXT_PUBLIC_HCLAW_TOKEN_ADDRESS}"
ENV NEXT_PUBLIC_HCLAW_TOKEN_ADDRESS_MAINNET="${NEXT_PUBLIC_HCLAW_TOKEN_ADDRESS_MAINNET}"
ENV NEXT_PUBLIC_HCLAW_TOKEN_ADDRESS_TESTNET="${NEXT_PUBLIC_HCLAW_TOKEN_ADDRESS_TESTNET}"
ENV NEXT_PUBLIC_MONAD_MAINNET_HCLAW_TOKEN_ADDRESS="${NEXT_PUBLIC_MONAD_MAINNET_HCLAW_TOKEN_ADDRESS}"
ENV NEXT_PUBLIC_MONAD_TESTNET_HCLAW_TOKEN_ADDRESS="${NEXT_PUBLIC_MONAD_TESTNET_HCLAW_TOKEN_ADDRESS}"
ENV NEXT_PUBLIC_HCLAW_LOCK_ADDRESS="${NEXT_PUBLIC_HCLAW_LOCK_ADDRESS}"
ENV NEXT_PUBLIC_HCLAW_LOCK_ADDRESS_MAINNET="${NEXT_PUBLIC_HCLAW_LOCK_ADDRESS_MAINNET}"
ENV NEXT_PUBLIC_HCLAW_LOCK_ADDRESS_TESTNET="${NEXT_PUBLIC_HCLAW_LOCK_ADDRESS_TESTNET}"
ENV NEXT_PUBLIC_MONAD_MAINNET_HCLAW_LOCK_ADDRESS="${NEXT_PUBLIC_MONAD_MAINNET_HCLAW_LOCK_ADDRESS}"
ENV NEXT_PUBLIC_MONAD_TESTNET_HCLAW_LOCK_ADDRESS="${NEXT_PUBLIC_MONAD_TESTNET_HCLAW_LOCK_ADDRESS}"
ENV NEXT_PUBLIC_HCLAW_POLICY_ADDRESS="${NEXT_PUBLIC_HCLAW_POLICY_ADDRESS}"
ENV NEXT_PUBLIC_HCLAW_REWARDS_ADDRESS="${NEXT_PUBLIC_HCLAW_REWARDS_ADDRESS}"
ENV NEXT_PUBLIC_AGENTIC_LP_VAULT_ADDRESS="${NEXT_PUBLIC_AGENTIC_LP_VAULT_ADDRESS}"
ENV NEXT_PUBLIC_BUILDER_ADDRESS="${NEXT_PUBLIC_BUILDER_ADDRESS}"
ENV NEXT_PUBLIC_BUILDER_FEE="${NEXT_PUBLIC_BUILDER_FEE}"

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:20-bookworm-slim AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
# Railway and most PaaS set PORT at runtime
ENV PORT=3000

RUN groupadd --gid 1001 nodejs \
  && useradd --uid 1001 --gid 1001 --create-home hyperclaw

COPY --from=deps /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/next.config.mjs ./next.config.mjs

RUN mkdir -p /app/.data \
  && chown -R hyperclaw:nodejs /app

USER hyperclaw

EXPOSE 3000

# Next.js reads PORT from env (Railway sets it automatically)
CMD ["npm", "run", "start", "--", "-H", "0.0.0.0"]
